---
#
# Ansible managed
#
repository:
  description: Create partitions, volume groups, volumes, filesystems and mounts
  homepage: https://robertdebock.nl/
  topics: storage, system, ansible, molecule, tox, playbook
