---

- name: filesystem | Test storage_filesystems
  ansible.builtin.assert:
    that:
      - filesystem.name is defined
    quiet: yes

- name: filesystem | Create filesystems
  community.general.filesystem:
    dev: "{{ filesystem.name }}"
    fstype: "{{ filesystem.fstype | default(storage_default_fstype) }}"
  notify:
    - Reload systemd

- name: filessytem | Run handlers
  ansible.builtin.meta: flush_handlers
