---
- name: test storage_filesystems
  assert:
    that:
      - filesystem.name is defined
    quiet: yes

- name: create filesystems
  filesystem:
    dev: "{{ filesystem.name }}"
    fstype: "{{ filesystem.fstype | default(storage_default_fstype) }}"
