---
# tasks file for storage
- name: install requirements
  package:
    name: "{{ storage_requirements }}"
    state: present
  register: storage_install_requirements
  until: storage_install_requirements is succeeded
  retries: 3

- name: find scsi busses
  find:
    path: /sys/class/scsi_host
    patterns: 'host*'
  register: storage_scsi_busses

- name: scan scsi bus
  lineinfile:
    path: "{{ item.path }}"
    line: "- - -"
  loop: "{{ storage_scsi_busses.files }}"
  changed_when: no

- name: include partition
  include: partition.yml
  with_items:
    - "{{ storage_partitions }}"
  loop_control:
    loop_var: partition
  when:
    - storage_partitions is defined

- name: include volumegroup
  include: volumegroup.yml
  with_items:
    - "{{ storage_volumegroups }}"
  loop_control:
    loop_var: volumegroup
  when:
    - storage_volumegroups is defined

- name: include volume
  include: volume.yml
  with_items:
    - "{{ storage_volumes }}"
  loop_control:
    loop_var: volume
  when:
    - storage_volumes is defined

- name: include filesystem
  include: filesystem.yml
  with_items:
    - "{{ storage_filesystems }}"
  loop_control:
    loop_var: filesystem
  when:
    - storage_filesystems is defined

- name: include mount
  include: mount.yml
  with_items:
    - "{{ storage_mounts }}"
  loop_control:
    loop_var: mount
  when:
    - storage_mounts is defined
