---
# tasks file for storage
- name: test veriables and environment
  assert:
    that:
      - storage_package_state is defined
      - storage_package_state == "present" or
        storage_package_state == "latest" or
        storage_package_state == "absent"

- name: install requirements
  package:
    name: "{{ storage_requirements }}"
    state: "{{ storage_package_state }}"
  register: storage_install_requirements
  until: storage_install_requirements is succeeded
  retries: 3

- name: include partition
  include: partition.yml
  with_items:
    - "{{ storage_partitions }}"
  loop_control:
    loop_var: partition
  when:
    - storage_partitions is defined

- name: show shit
  debug:
    var: storage_volumegroups

- name: include volumegroup
  include: volumegroup.yml
  with_items:
    - "{{ storage_volumegroups }}"
  loop_control:
    loop_var: volumegroup
  when:
    - storage_volumes is defined

- name: include volume
  include: volume.yml
  with_items:
    - "{{ storage_volumes }}"
  loop_control:
    loop_var: volume
  when:
    - storage_volumes is defined

- name: include filesystem
  include: filesystem.yml
  with_items:
    - "{{ storage_filesystems }}"
  loop_control:
    loop_var: filesystem
  when:
    - storage_mounts is defined

- name: include mount
  include: mount.yml
  with_items:
    - "{{ storage_mounts }}"
  loop_control:
    loop_var: mount
  when:
    - storage_mounts is defined
