---
- name: test volumegroup
  assert:
    that:
      - volumegroup.name is defined
      - volumegroup.device is defined
    quiet: yes

- name: create volume groups
  lvg:
    vg: "{{ volumegroup.name }}"
    pvs: "{{ volumegroup.devices | join(', ') }}"
    pesize: "{{ volumegroup.size | default(omit) }}"
