---
- name: test volumegroup
  assert:
    that:
      - volumegroup.name is defined
      - volumegroup.device is defined
      - volumegroup.size is defined
      - volumegroup.size | int
    quiet: yes

- name: create volume groups
  lvg:
    vg: "{{ volumegroup.name }}"
    pvs: "{{ volumegroup.device }}"
    pesize: "{{ volumegroup.size | default(omit) }}"
