---
# handlers file for storage
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: refresh facts
  setup:

- name: include mount
  include: mount.yml
  loop: "{{ storage_mounts }}"
  loop_control:
    loop_var: mount
  when:
    - storage_mounts is defined
