---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: storage-fedora
    box: fedora/29-cloud-base
    instance_raw_config_args:
      - "storage :file, :size => '20G'"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
